version: '3'
services:
  postgre:
    build:
      context: ./containers/postgre
    ports:
      - "5432:5432"
    image: wst_1_postgre_image
    container_name: postgre4
  glassfish:
    build:
     context: ./containers/glassfish
    image: wst_1_glassfish_image
    container_name: glassfish4
    links:
      - postgre
    depends_on:
      - postgre
    ports:
      - 8080:8080
      - 4848:4848
      - 8181:8181


